
# Site settings
title: JU Blog :)
email: juhwacheol@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  every single day, 
#baseurl: "/labrador-jekyll-theme" # the subpath of your site, e.g. /blog
url:  ""
logo: "/assets/img/icon-1000.png"

# Build settings
paginate: 10
paginate_path: "/blog/page:num/"
markdown: kramdown
sass:
    sass_dir: assets/css/sass
    style: compressed

gems:
  - jekyll-gist
  - jekyll-paginate
