
# Site settings
title: JU Blog :)
email: juhwacheol@gmail.com
description1: > 
Yesterday,
description2: > 
Today,
description3: > 
Tomorrow, Coding too
#baseurl: "/labrador-jekyll-theme" # the subpath of your site, e.g. /blog
url:  ""
homeurl: "https://juhwacheol.github.io/en/"
logo: "/assets/img/icon-1000.png"

# Build settings
paginate: 10
paginate_path: "/blog/page:num/"
markdown: kramdown
sass:
    sass_dir: assets/css/sass
    style: compressed

gems:
  - jekyll-gist
  - jekyll-paginate
