# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rodrigo Donini
email: me@donini.me
description: > # this means to ignore newlines until "baseurl:"
  Empreendedor e Full Stack Developer, apaixonado por tecnologia, Rodrigo S. Donini.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://donini.me" # the base hostname & protocol for your site
logo: "/assets/img/logo.png"

# Build settings
markdown: kramdown
sass:
    sass_dir: assets/css/sass
    style: compressed